version: "3.8"

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root # 플러그인 설치나 권한 문제 방지를 위해 root 권한으로 실행(선택사항)
    ports:
      - "8080:8080" # Jenkins 웹 UI
      - "50000:50000" # 에이전트 통신 포트
    volumes:
      - nginx_jenkins_home:/var/jenkins_home # 데이터 유지용 볼륨
      - /var/run/docker.sock:/var/run/docker.sock # 도커 명령어 사용을 위해 호스트 도커 소켓 공유 (필요시)
    restart: unless-stopped
    expose:
      - "8080"
    networks:
      - jenkins-net
      - proxy-net

volumes:
  nginx_jenkins_home:

networks:
  jenkins-net:
    external: true
  proxy-net:
    external: true
