version: "3.8"

services:
  jenkins:
    image: ventileco/custom-jenkins:latest
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - nginx_jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    expose:
      - "8080"
    networks:
      - jenkins-net
      - proxy-net

volumes:
  nginx_jenkins_home:

networks:
  jenkins-net:
    external: true
  proxy-net:
    external: true
