version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/www:/var/www/certbot
      - ./nginx/ssl:/etc/letsencrypt
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/ssl:/etc/letsencrypt
      - ./nginx/www:/var/www/certbot
    entrypoint: /bin/sh

  interverse-api:
    image: ventileco/interverse-api-server:latest
    container_name: interverse-api
    expose:
      - "8000"
    restart: unless-stopped

  interverse-socket:
    image: ventileco/interverse-socket-server:latest
    container_name: interverse-socket
    expose:
      - "8001"
    restart: unless-stopped
